micronaut:
  application:
    name: Gallery
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
netty:
  default:
    allocator:
      max-order: 3

db:
  name: 'picture'
  collection: 'picture'
